### PR TITLE
added hex temp workaround

### PR DESCRIPTION
**Pull request by kzidane**

### CODE REVIEW

**Comment by kzidane** [comment]
@dmalan **Open hex** is mentioned in a couple of other places later in the adoc. Want me to add this bit there too?

**Comment by dmalan** [comment]
Mind opening Issue to remove this sentence once other PR deploys?

**Comment by dmalan** [comment]
Only need to mention where we mention adjusting those values, which I think is just in one place.

**Comment by kzidane** [comment]
https://github.com/cs50/docs/issues/175

**Pull request merged**
