### PR TITLE
updates "What's New?" [skip ci]

### PR DESCRIPTION
**Pull request by kzidane**
@dmalan, how do these look initially?

### CODE REVIEW

**Comment by kzidane** [comment]
new

**Comment by dmalan** [comment]
Mind making them full sentences, explaining how to achieve equivalent
functionality after? (And do surround commands in back ticks.)

**Comment by kzidane** [comment]
Oh! I thought you wanted to keep it simple per the examples in that Asana. Any particular format you prefer? For example:

> -  No more ⓘ icon; use `username50` to get your username, and `password50` to get your MySQL password!

?

**Comment by dmalan** [comment]
That looks good!

**Comment by kzidane** [comment]
Want a brief explanation for the new tools? For example: 

> - `help50` — helps you understand error messages

**Comment by dmalan** [comment]
Sure.

**Comment by kzidane** [comment]
new-updated

**Comment by kzidane** [comment]
@dmalan any other thoughts?

**Comment by dmalan** [comment]
:shipit:

**Comment by kzidane** [comment]
Merged per 1e1abea0a1!

**Pull request closed without merging**
