### PR TITLE
Vigenere - Add newline requirement

### PR DESCRIPTION
**Pull request by curiouskiwi**
Added newline requirement per check50 test.

### CODE REVIEW

**Comment by curiouskiwi** [comment]
Just thought of this. Do we need to update the changelog on this page (and caesar's)?  I can do that if needed.

**Comment by dlloyd09** [comment]
Oh yes, we should do that too! ty!

**Comment by curiouskiwi** [comment]
@dlloyd09 Two new PRs for the changelog have been done. :)

**Comment by dmalan** [comment]
Thanks!

**Pull request merged**
