### PR TITLE
fix pset6 similarities less text

### PR DESCRIPTION
**Pull request by Aternus**

### CODE REVIEW

**Comment by dmalan** [comment]
Not sure this PR changes the semantics of the instructions?

**Comment by dmalan** [comment]
Both! Afraid I don't see what problem this solves! Seems grammatically correct as is?

**Comment by Aternus** [comment]
I thought that it wasn't clear and required a review, but perhaps my English is not as good as I thought it is. Thank you for teaching me one more thing! @dmalan 😁

**Comment by dmalan** [comment]
Ah, gotcha. Thank you!

**Pull request closed without merging**
