### PR TITLE
update final project submission

### PR DESCRIPTION
**Pull request by curiouskiwi**
Added a bit more to make it clear that project source code should not be submitted.

### CODE REVIEW

**Comment by curiouskiwi** [comment]
@dmalan please review my wording. :)

**Comment by dlloyd09** [comment]
@curiouskiwi I don't understand why we should outright prohibit folks from submitting code?

**Comment by curiouskiwi** [comment]
@dlloyd09 we've had lots of problems with the `check50` for the final project failing / timing out because folks upload 1000s of files, particularly if they've used a lot of external libraries with lots of small files and images, etc.  @brianyu28 might know more, but this was to try to avoid the "I never got my grade" problems.   Perhaps we should just say " you aren't required to submit your code "?

**Comment by dlloyd09** [comment]
I personally think we should still collect the code if we can, potentially
useful for general academic honesty use. Maybe we can tweak the wording to
something like "If your code exceeds 50MB in total size or you have more
than 1,000 files total, submit50 may not be able to handle your project; in
that case, it suffices to only share your video using the instructions
below"?

**Comment by curiouskiwi** [comment]
We've never required edX students to submit code, particularly if they've developed their project outside of the IDE.  In 2018, we added the requirement of running `submit50` in order to have a grade.  This caused confusion because many students had no `project` folder and hadn't used the IDE for their project.  The advice became "create a file that describes your project and submit that." 
 So for 2019,  to mitigate that confusion, we made that explicit by asking them to create and submit a `README.md` file.   I'm fine with asking for code if that's preferred.

**Comment by dlloyd09** [comment]
I personally think we should still collect the code if we can. Maybe we can tweak the wording to something like "If your code exceeds 50MB in total size or you have more than 1,000 files total, submit50 may not be able to handle your project; in that case, it suffices to only share your video using the instructions below"?

**Comment by dlloyd09** [comment]
Actually I withdraw this, maybe it's more trouble than it's worth. It would be nice for people to be able to submit, but I can see the potential for headaches.

**Comment by curiouskiwi** [comment]
I removed the "must not" and changed it to "not required"  Also added a bit about the gradebook so if any student runs into the "grade not showing", they know what to do.  How's that?

**Comment by dmalan** [comment]
Let me reassign this to @dlloyd09!

**Pull request merged**
