### PR TITLE
Auto deployment

### PR DESCRIPTION
**Pull request by kzidane**
**Usage should be as easy as:**
1. edit `2016/*`
2. `git add ...`
3. `git commit -m "..."`
4. `git push origin master`

**To view changes:**
1. `make image` once
2. `make container`
3. `make docs`
4. the generated files should be under  `/root/docs/`, inside the container, or `docs/` in the repo

Messages of the commits that do not affect the generated files should contain `[skip ci]` in order not to trigger a build, which would fail, because there would be no changes to deploy.

@dmalan thoughts?

### CODE REVIEW

**Comment by dmalan** [comment]
Does `Gemfile.lock` need to be committed? Does `pygments.rb` no longer need to be explicitly installed?

**Comment by kzidane** [comment]
`Gemfile.lock` is recommended to stay in the repo per http://stackoverflow.com/a/4151540/1797347? Though I don't think it's a must. 

Added `pygments.rb` back and removed `jekyll`, as automatically installed as a dependency for `jekyll-asciidoc`.

Actually there's one problem that I just noticed, and that's why I had `docs` out of the repo (in `/tmp`) previously, but I totally forgot about — how to move `docs/*` from `master` to `gh-pages` :unamused:. Rethinking ...

**Comment by dmalan** [comment]
Re moving, https://gist.github.com/domenic/ec8b0fc8ab45f39403dd?

**Comment by kzidane** [comment]
Not sure if that script is more complicated than needed. I used to simply

```
git fetch origin gh-pages:gh-pages
git checkout gh-pages
rm -rf *
...
```

Thinking to `cp -r docs /tmp/docs50 && git checkout gh-pages && rm -rf * && cp -r /tmp/docs50/* .`. What do you think?

**Comment by dmalan** [comment]
Doing mv instead of cp would be faster!

**Comment by kzidane** [comment]
@dmalan, created a deployment pipeline for the auto-deployment branch. docs.cs50.net is live from the gh-pages branch now. TOC is back. No noticeable issues.

(http://docs.cs50.net/2016/fall/psets/0/pset0.html)

Feel free to test by pulling down auto-deployment, making changes, and pushing! Don't forget to add `[skip ci]` to the commit message, if the commit doesn't affect `docs/*`. Though, ideally, there should be no harm, if you forget, other than the annoying "Build Failed" notification.

master is the same meanwhile, just in case there's something I'm missing. If anything goes wrong while testing, it would be as easy as switching back to deploy to GitHub pages from `docs/` in master.

**Comment by kzidane** [comment]
@dlloyd09 ^ fyi!

**Comment by dmalan** [comment]
Thank you!

**Pull request merged**
